foreground {{colors.on_background.default.hex}}
background {{colors.background.default.hex}}
cursor {{colors.primary.default.hex}}
selection_background {{colors.primary.default.hex}}
selection_foreground {{colors.on_primary.default.hex}}
color0  {{colors.surface.default.hex}}
color8  {{colors.outline.default.hex}}
color4  {{colors.primary.default.hex}}
color2  {{colors.tertiary.default.hex}}
